apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: replicaset1
  labels:
    app: rs
spec:
  ports:
  - port: 3306
    name: mysql-port
  clusterIP: None
  selector:
    app: rs
---
apiVersion: apps/v1beta
kind: StatefulSet
metadata:
  name: rsnode
spec:
  selector:
    matchLabels:
      app: rs
  serviceName: "replicaset1"
  replicas: 2
  template:
    metadata:
      labels:
        app: rs
    spec:
      initContainers:
      - name: init-mysql
        image: perconalab/percona-rs
        command: ["/bin/bash","/usr/bin/init-mysql.sh"]
        volumeMounts:
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: config-volume
          mountPath: /mnt/config-map
      - name: clone-mysql
        image: perconalab/percona-rs
        command: ["/bin/bash","/usr/bin/init-datadir.sh"]
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
          subPath: data
        - name: conf
          mountPath: /etc/mysql/conf.d
      containers:
      - name: mysql
        image:  perconalab/percona-rs
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command: ["/usr/bin/mysqlcheck.sh"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["/usr/bin/mysqlcheck.sh"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
          subPath: data
        - name: conf
          mountPath: /etc/mysql/conf.d/
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: root
          - name: XTRABACKUP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: xtrabackup
          - name: MONITOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-passwords
                key: monitor
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-volume
        configMap:
          name: mysql
          optional: true
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
