apiVersion: v1
kind: Secret
metadata:
  name: {{ template "percona.fullname" . }}
  labels:
    app: {{ template "percona.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  root:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  root: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  xtrabackup: {{ randAlphaNum 10 | b64enc | quote }}
  monitor: {{ randAlphaNum 10 | b64enc | quote }}
  clustercheck: {{ randAlphaNum 10 | b64enc | quote }}
  proxyuser: {{ randAlphaNum 10 | b64enc | quote }}
